GET http://localhost:5000/dogs

###

GET http://localhost:5000/dogs/731

###

POST http://localhost:5000/dogs
Content-Type: application/json

{
    "name": "Eros",
    "breed":"Blandis",
    "age":"14"
}

###

PUT http://localhost:5000/dogs/136
Content-Type: application/json

{
    "name": "Oswald",
    "breed": "Chihuahua",
    "age": "10"
}

###
DELETE http://localhost:5000/dogs/731