GET http://localhost:5000/api/dogs

###

GET http://localhost:5000/api/dogs/740

###

POST http://localhost:5000/api/dogs
Content-Type: application/json

{
    "name": "Furion",
    "breed":"Corgi",
    "age":"1"
}

###

PUT http://localhost:5000/api/dogs/199
Content-Type: application/json

{
    "name": "Ozzy",
    "breed": "Chihuahua",
    "age": "9"
}

###
DELETE http://localhost:5000/api/dogs/257