GET http://localhost:5000/dogs

###

GET http://localhost:5000/dogs/1

###

POST http://localhost:5000/dogs
Content-Type: application/json

{
    "name": "Eros",
    "breed":"Blandis",
    "age":"14"
}

###

PUT http://localhost:5000/dogs/1
Content-Type: application/json

{
    "name": "Ninja",
    "breed": "sheltie",
    "age": "10"
}

###
DELETE http://localhost:5000/dogs/731